[workspace]
members = [
    "templates/poc/node",
    "templates/poc/runtime",

    "templates/mvp/node/cli",
    "templates/mvp/node/executor",
    "templates/mvp/node/inspect",
    "templates/mvp/node/primitives",
    "templates/mvp/node/rpc",
    "templates/mvp/node/testing",
    "templates/mvp/runtime",

    "pallets/template",

]
[profile.release]
panic = "unwind"
